services:
  webapp:
    build: ./app
    ports:
      - "8855:8000"
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    networks:
      - shared-net

  indexer:
    build: ./app
    command: >
      python /scripts/index_qdrant.py --docs /data/documents.jsonl
    volumes:
      - ./scripts:/scripts:ro
      - ./data:/data:ro
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=intfloat/multilingual-e5-small
    profiles:
      - index
    networks:
      - shared-net

networks:
  shared-net:
    external: true
